-- Diferencia títulos de plantillas RMN asociadas a study types distintos.

BEGIN;

UPDATE nextris.tbinfpredef ip
SET tittle = CASE st.code
    WHEN '3109' THEN 'RESONANCIA MAGNÉTICA DE MUSLO SIN CONTRASTE'
    WHEN '3119' THEN 'RESONANCIA MAGNÉTICA DE MUSLO CON CONTRASTE'
    WHEN '3113' THEN 'RESONANCIA MAGNÉTICA DE PIERNA SIN CONTRASTE'
    WHEN '3121' THEN 'RESONANCIA MAGNÉTICA DE PIERNA CON CONTRASTE'
    WHEN '3148' THEN 'RM DE PLEXO BRAQUIAL BILATERAL CON Y SIN CONTRASTE EV'
    WHEN '3149' THEN 'RM DE PLEXO BRAQUIAL UNILATERAL CON Y SIN CONTRASTE EV'
END
FROM nextris.isstudytype st
WHERE st.guid = ip.studytype_id
  AND st.code IN ('3109', '3119', '3113', '3121', '3148', '3149');

COMMIT;
